# Generated by Django 3.2.5 on 2024-01-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekken_persons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persongame',
            name='description',
            field=models.TextField(blank=True, verbose_name='Укажите описание'),
        ),
    ]
