# Generated by Django 3.2.5 on 2024-01-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekken_persons', '0002_persongame_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persongame',
            old_name='name',
            new_name='name1',
        ),
        migrations.AlterField(
            model_name='persongame',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Укажите описание'),
        ),
    ]
