# Generated by Django 3.2.5 on 2024-01-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tekken_persons', '0004_auto_20240119_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persongame',
            options={'verbose_name': 'Персонажа', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterField(
            model_name='persongame',
            name='name1',
            field=models.CharField(max_length=30, null=True, verbose_name='Укажите имя персонажа'),
        ),
    ]
