# Generated by Django 3.2.5 on 2024-01-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tekken_persons', '0005_auto_20240119_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persongame',
            old_name='email1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='persongame',
            old_name='name1',
            new_name='name',
        ),
    ]
